version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        applies-to: version-updates
        patters: ["*"]
        update-types:
        - minor
        - patch
      all-major:
        applies-to: version-updates
        patters: ["*"]
        update-types:
        - major
