name: CI

on:
  push:
    branches:
      - master
      - renovate/*
  pull_request:
    branches:
      '*'

env:
  FORCE_COLOR: 3

jobs:
  # unit:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: lts/*
  #       cache: yarn
  #     env:
  #       FORCE_COLOR: 0
  #   - name: Install Dependencies
  #     run: yarn install --frozen-lockfile --prefer-offline
  #   - name: Unit Tests
  #     run: yarn test:unit
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: yarn
      env:
        FORCE_COLOR: 0
    - name: Install dependencies
      run: yarn install --frozen-lockfile --prefer-offline
    - name: Lint and Typecheck
      run: yarn lint
